ALTER TABLE COLLECTION
ADD COLUMN IGNORED_TRAIT_TYPES_RARITY VARCHAR[] NOT NULL DEFAULT array[]::varchar[];

ALTER TABLE COLLECTION
ADD COLUMN IGNORED_TRAIT_TYPES_OVERLAP VARCHAR[] NOT NULL DEFAULT array[]::varchar[];