ALTER TABLE COLLECTION
ADD COLUMN IGNORED_TRAIT_TYPES VARCHAR[] NOT NULL DEFAULT array[]::varchar[];

ALTER TABLE COLLECTION
ADD COLUMN IGNORED_TRAIT_VALUES VARCHAR[] NOT NULL DEFAULT array[]::varchar[];